### ISSUE TITLE
How to set paths for inputs and outputs

### ISSUE THREAD

**Issue by grandas** [daPhyre/brackets-jscompiler#10]
Hey,

Great plugin! 
Is there a  way to define paths for inputs and outputs using the .brackets.json file?

I've tried using this in the file but it didn't work: 

```
"jscompiler": {
        "outputs": [
            {
                "inputs": ["js/munchkin.js", "js/doccookies.js", "js/app.js"],
                "output": "app.min.js",
                "generateMap": true,
                "mangle": true,
                "isolate": false
            }
        ]     
    }
```

**Comment by daPhyre** [comment]
It should work like that, there must be a bug on the code. Let me check on it.

**Comment by daPhyre** [comment]
Thanks for your feedback, the bug has been fixed.

**Comment by grandas** [comment]
Works great, thanks!
