### ISSUE TITLE
Multiple Input and Outputs

### ISSUE THREAD

**Issue by mrevjd** [daPhyre/brackets-jscompiler#15]
I have a project that uses multiple js files. A js file is loaded depending on what page is calling it.
Is it possible to have different multiple input files with the equivalent out file.
Eg:
    "jscompiler": {
        "outputs": [
            {
                "inputs": [
                    "includes/setup.js"
                ],
                "output": "includes/setup.min.js",
                "generateMap": true,
                "mangle": true,
                "isolate": false
            },
            {
                "inputs": [
                    "includes/custom.js"
                ],
                "output": "includes/custom.min.js",
                "generateMap": true,
                "mangle": true,
                "isolate": false
            },
	]
    }

Thanks

**Comment by daPhyre** [comment]
Yes you can! And if this is your goal, you can let it take all the default values with the minimal configuration, like this:

"jscompiler": {
"outputs": [
{
"inputs": ["includes/setup.js"]
},
{
"inputs": ["includes/custom.js"]
},
]
}

**Comment by mrevjd** [comment]
Thanks for the quick response.
Will this create multiple output files or just compile them all into a single file.
