### ISSUE TITLE
Use .brackets.json for options

### ISSUE THREAD

**Issue by mrmckeb** [daPhyre/brackets-jscompiler#4]
Brackets supports the use of a .brackets.json file in the root directory. This can hold settings for a number of plugins, for example brackets-sass uses it like so:

```JSON
{
    "path": {
        "scss/*.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css/",
                "outputStyle": "compressed"
            }
        }
    }
}
```

**Comment by daPhyre** [comment]
Progress:

`prefs.set("jscompiler", {"test": "output.min.js"});` - Saves the information on the user preferences. This makes little sense for the extension, as we require to have different information for each project.

`prefs.set("jscompiler", {"test": "output.min.js"}, {location: {scope: "project"}});` - Crashes the extension, and becomes useless... Is this really the way to save information on the project preferences file? Found no documentation about this. Haven't found either an alternative to save project preferences.

`console.log(PreferencesManager.get("jscompiler"));` - Reads successfully the information from the user preferences (Again, there is no use on it on this extension), doesn't read information from the project preferences. Haven't found a way to do so.

**Comment by daPhyre** [comment]
Done in v1.9.9.
