### ISSUE TITLE
Minified script doesn't include Source Map comment

### ISSUE THREAD

**Issue by mrmckeb** [daPhyre/brackets-jscompiler#7]
Great plugin, we're using this a lot here. The only issue we have is that the output doesn't include the link to the source-map.

Without this, the map file is never loaded. We're currently doing this manually, but it would be great if you could add this in. If you'd like, we could do it and you could merge the change?

```javascript
//# sourceMappingURL=script.min.js.map
```

**Comment by daPhyre** [comment]
Will appear on the next release, but it may take some time as I'm in the middle of 2.0 release. I hope you can make a local fix meanwhile, and thank you for the data!

**Comment by mrmckeb** [comment]
Amazing. Do you have a new icon for the next release? I have something in mind if you're open to it?

**Comment by daPhyre** [comment]
New icon? Currently the extension has no icon, and I have not consider it to have one... What do you have in mind?

**Comment by daPhyre** [comment]
Found a way to release a pending feature without making incompatible the next release with previous versions, therefore v2.0.0 can wait for later, and this bug has been fixed in v1.9.3.
